apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-students
  namespace: colegio-ohiggins
  labels:
    app: ms-students
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-students
  template:
    metadata:
      labels:
        app: ms-students
        tier: backend
    spec:
      containers:
        - name: ms-students
          image: colegio-ohiggins-ms-students:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: colegio-ohiggins-secret
                  key: SPRING_DATASOURCE_PASSWORD
          envFrom:
            - configMapRef:
                name: colegio-ohiggins-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
