apiVersion: v1
kind: Service
metadata:
  name: ms-students
  namespace: colegio-ohiggins
  labels:
    app: ms-students
    tier: backend
spec:
  selector:
    app: ms-students
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
