apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: colegio-ohiggins
  labels:
    app: admin-server
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
        tier: monitoring
    spec:
      containers:
        - name: admin-server
          image: colegio-ohiggins-admin-server:latest
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: colegio-ohiggins-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
