apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: colegio-ohiggins
  labels:
    app: admin-server
    tier: monitoring
spec:
  selector:
    app: admin-server
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
