apiVersion: v1
kind: Service
metadata:
  name: backend-bff
  namespace: colegio-ohiggins
  labels:
    app: backend-bff
    tier: edge
spec:
  selector:
    app: backend-bff
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
