apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: colegio-ohiggins
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: colegio-ohiggins-frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: colegio-ohiggins-config
                  key: VITE_API_URL
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
