apiVersion: v1
kind: Secret
metadata:
  name: colegio-ohiggins-secret
  namespace: colegio-ohiggins
type: Opaque
data:
  # Generar con: echo -n "valor" | base64
  # En producción real usar AWS Secrets Manager o Sealed Secrets
  DB_PASSWORD: T2hpZ2dpbnNfU2VjdXIzXzIwMjYh
  SPRING_DATASOURCE_PASSWORD: T2hpZ2dpbnNfU2VjdXIzXzIwMjYh
  MYSQL_ROOT_PASSWORD: T2hpZ2dpbnNfU2VjdXIzXzIwMjYh
  MYSQL_PASSWORD: T2hpZ2dpbnNfU2VjdXIzXzIwMjYh
  JWT_SECRET: T2dIMWc0RzNTczNjdVSjBGckpXdFQwazNuUzFnbjFuRzFzVjNyeUwwbkc0bmRTM2NyMw==
