# Nombre de la aplicación
spring.application.name=backend-bff

# Puerto del Gateway (Punto de entrada único)
server.port=8080

# Configuración de rutas del API Gateway
# Enrutamiento hacia ms-students
spring.cloud.gateway.mvc.routes[0].id=students-route
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/students/**

# Enrutamiento hacia ms-attendance
spring.cloud.gateway.mvc.routes[1].id=attendance-route
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/attendance/**

# Enrutamiento hacia ms-communications
spring.cloud.gateway.mvc.routes[2].id=communications-route
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/communications/**